import { Octokit } from 'octokit';

export class GitHubNotifier {
  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN
    });
    this.owner = process.env.GITHUB_REPOSITORY?.split('/')[0];
    this.repo = process.env.GITHUB_REPOSITORY?.split('/')[1];
  }

  /**
   * Create GitHub issue for bot activity
   */
  async createIssue(title, body, labels = []) {
    try {
      const response = await this.octokit.rest.issues.create({
        owner: this.owner,
        repo: this.repo,
        title,
        body,
        labels
      });

      console.log(`✅ Issue created: #${response.data.number}`);
      return response.data;
    } catch (error) {
      console.error('Failed to create issue:', error);
      throw error;
    }
  }

  /**
   * Post comment on issue
   */
  async commentOnIssue(issueNumber, comment) {
    try {
      const response = await this.octokit.rest.issues.createComment({
        owner: this.owner,
        repo: this.repo,
        issue_number: issueNumber,
        body: comment
      });

      console.log(`✅ Comment posted on #${issueNumber}`);
      return response.data;
    } catch (error) {
      console.error('Failed to post comment:', error);
    }
  }

  /**
   * Report monetization status
   */
  async reportMonetizationStatus(data) {
    const body = `
## 💰 Monetization Status Report

**Date:** ${new Date().toLocaleString()}

### Revenue Metrics
- **Estimated Revenue:** $${data.estimatedRevenue.toFixed(2)}
- **Ad Impressions:** ${data.adImpressions.toLocaleString()}
- **CTR:** ${data.ctr.toFixed(2)}%
- **CPM:** $${data.cpm.toFixed(2)}
- **RPM:** $${data.rpm.toFixed(2)}

### Recommendations
${data.recommendations.map(r => `- ${r}`).join('\n')}

---
*Generated by YouTube Event Bot*
    `;

    await this.createIssue(
      '📊 Monthly Monetization Report',
      body,
      ['monetization', 'report']
    );
  }

  /**
   * Report video upload status
   */
  async reportVideoUploadStatus(videoCount, errors = []) {
    let body = `
## 📹 Video Upload Report

**Date:** ${new Date().toLocaleString()}
**Videos Uploaded:** ${videoCount}

    `;

    if (errors.length > 0) {
      body += `
### Errors
${errors.map(e => `- ${e}`).join('\n')}
      `;
    } else {
      body += '\n✅ All videos uploaded successfully!';
    }

    await this.createIssue(
      `📹 Video Upload Status - ${videoCount} videos`,
      body,
      ['upload', 'automation']
    );
  }

  /**
   * Report comment moderation activity
   */
  async reportModerationStatus(stats) {
    const body = `
## 🗨️ Comment Moderation Report

**Date:** ${new Date().toLocaleString()}

### Statistics
- **Reviewed:** ${stats.reviewed}
- **Spam Detected:** ${stats.spam}
- **Approved:** ${stats.approved}
- **Held for Review:** ${stats.held}

---
*Generated by YouTube Event Bot*
    `;

    await this.createIssue(
      '🗨️ Daily Moderation Report',
      body,
      ['moderation', 'report']
    );
  }
}
